oxygen: Temporarily allow org.codeaurora.ims privileges (TMP)
Error: Signature|privileged permissions not in privapp-permissions whitelist: org.codeaurora.ims (/system/system_ext/priv-app/ims): android.permission.WRITE_SECURE_SETTINGS, org.codeaurora.ims (/system/system_ext/priv-app/ims): android.permission.READ_PRIVILEGED_PHONE_STATE, org.codeaurora.ims (/system/system_ext/priv-app/ims): android.permission.MODIFY_PHONE_STATE

* As of Android 9, implementors must explicitly grant or deny all privileged permissions or the device won’t boot.

See https://source.android.com/devices/tech/config/perms-allowlist for details